CREATE TABLE IF NOT EXISTS ColorSerial(
  id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  colorname CHAR(8),
  alpha_v TINYINT UNSIGNED,
  red_v TINYINT UNSIGNED,
  green_v TINYINT UNSIGNED,
  blue_v TINYINT UNSIGNED,
  time_s CHAR(11));

